version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  build:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run: composer install
      - run: npm ci
      - run: npm run build
      - run:
          name: php test
          command: vendor/bin/phpunit

  deploy:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - aws-cli/install
      - add_ssh_keys:
          fingerprints:
            - "${KEY_FINGERPRINT}"
      - run:
          name: create ssh rule
          command: aws ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr ${IP}/32
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no -t ec2-user@ec2-${HOST_NAME}.ap-northeast-1.compute.amazonaws.com "cd output_project && \
              git pull origin main && \
              composer install -n --no-dev --prefer-dist && \
              npm ci && \
              npm run build:prod && \
              php artisan migrate --force && \
              php artisan config:cache"
      - run:
          name: revoke ssh rule
          command: aws ec2 revoke-security-group-ingress --group-id ${SECURITY_GROUP} --protocol tcp --port 22 --cidr ${IP}/32

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
