version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run: composer install
      - run: npm ci
      - run: npm run build
      - run:
          name: php test
          command: vendor/bin/phpunit

workflows:
  test-app:
    jobs:
      - build
